# Generated by Django 4.0.4 on 2022-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='images/default_profile.jpg', upload_to='images'),
        ),
    ]
