# Generated by Django 4.0.4 on 2022-07-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_like_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like_post',
            new_name='LikePost',
        ),
    ]
